### ISSUE TITLE
SPIFFS mount failure, 

### ISSUE THREAD

**Issue by Hassanphiri** [atomic14/diy-alexa#67]
here is the output serial monitor output:

Starting up
Total heap: 164564
Free heap: 95960
E (3410) SPIFFS: mount failed, -10025
[  2864][E][SPIFFS.cpp:89] begin(): Mounting SPIFFS failed! Error: -1
[  2877][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073559540 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073559540, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284     
[  2903][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073693784 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073693784, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284
[  2932][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073693836 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073693836, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284     
[  2962][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073693888 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073693888, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284
[  2991][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073693940 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073693940, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284     
[  3020][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073693992 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073693992, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284
[  3049][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073694044 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073694044, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284
[  3079][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073694096 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073694096, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284
[  3108][E][vfs_api.cpp:24] open(): File system is not mounted
ERROR: bit depth 16381 is not supported please use 16 bit signed integer
ERROR: bit depth 1073694148 is not supported please us 16KHz
fmt_chunk_size=0, audio_format=0, num_channels=0, sample_rate=1073694148, sample_alignment=-6784, bit_depth=16381, data_bytes=1073651284
Loading model
Used bytes 22600

Created Neral Net
m_pooled_energy_size=43
Created audio processor
Starting i2s
E (3697) I2S: register I2S object to platform failed
Guru Meditation Error: Core  0 panic'ed (Memory protection fault).
Write operation at address 0x3f41f000 not permitted (INVALID_MEM_TYPE)

Core  0 register dump:
PC      : 0x4002dc18  PS      : 0x00060034  A0      : 0x80084748  A1      : 0x3ff9ed10
A2      : 0x2d203a72  A3      : 0x3ff9ed54  A4      : 0x2d203abe  A5      : 0x3ffd388c
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x8002dc15  A9      : 0x3ff9ecf0  
A10     : 0x00000001  A11     : 0xffffffff  A12     : 0x00060023  A13     : 0x80000000  
A14     : 0x00000000  A15     : 0xffffffff  SAR     : 0x00000000  EXCCAUSE: 0x00000007
EXCVADDR: 0x00000000  LBEG    : 0x00060023  LEND    : 0x80000000  LCOUNT  : 0x40026e19  

Backtrace: 0x4002dc15:0x3ff9ed10 0x40084745:0x3ff9ed50
  #0  0x4002dc15 in xQueueReceive at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1402
  #1  0x40084745 in i2sReaderTask(void*) at lib/audio_input/I2SSampler.cpp:25

ELF file SHA256: 219b4f25e866f494

Rebooting...
ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x3 (RTC_SW_SYS_RST),boot:0x9 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40026c8d
  #0  0x40026c8d in esp_restart_noos_dig at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:53 (discriminator 1)

**Comment by Hassanphiri** [comment]
please help! am using esp32-s2

**Comment by Hassanphiri** [comment]
Thanks for the platform and help, I managed to mount the SPIFFS .
